# Generated by Django 4.1.2 on 2022-10-31 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='runReviews',
            new_name='numReviews',
        ),
    ]
