# Generated by Django 4.1.2 on 2022-10-31 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_runreviews_product_numreviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
